"""Add test_field to torney table

Revision ID: 0c2cd02dc1bb
Revises: 6623b90fbfc8
Create Date: 2025-07-29 19:53:07.248403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c2cd02dc1bb'
down_revision: Union[str, Sequence[str], None] = '878315ce9602'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('torney', sa.Column('test_field', sa.VARCHAR(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('torney', 'test_field')
    # ### end Alembic commands ###
