"""Remove test_field from torney table

Revision ID: ae12e318dccc
Revises: 0c2cd02dc1bb
Create Date: 2025-07-29 19:55:38.633700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae12e318dccc'
down_revision: Union[str, Sequence[str], None] = '0c2cd02dc1bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('torney', 'test_field')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('torney', sa.Column('test_field', sa.VARCHAR(length=100), nullable=True))
    # ### end Alembic commands ###
